swagger: '2.0'
info:
  version: '1.0.0'
  title: Registrar informações sobre o crescimento dos pacientes
  description: Especificação 'Registrar informações sobre o crescimento dos pacientes' do curso Implantando e Gerenciando o Apigee do Google
  contact:
    email: cleison@estiatraining.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: suport-eval-prod.apigee.net
basePath: /registrar-info-cresc-pacientes/v1
schemes:
  - http
  - https
tags:
  - name: Criança Specs
    description: Tudo sobre a especificação 'Registrar informações sobre o crescimento dos pacientes'
security:
  - token: []
paths:
  /progress:
    get:
      tags:
        - Criança Specs
      summary: Recuperar todos os progressos
      operationId: getProgress
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/body_response'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/body_response_error_401'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/body_response_error_500'
    post:
      tags:
        - Criança Specs
      summary: Cria um novo progresso
      operationId: postProgress
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: progress
          description: Persiste um novo progresso de crescimento do paciente
          required: true
          schema:
            $ref: '#/definitions/body_request'
      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/body_response'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/body_response_error_400'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/body_response_error_401'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/body_response_error_500'
  /progress/{id}:
    get:
      tags:
        - Criança Specs
      summary: Recupera um progresso pelo ID
      operationId: getProgressById
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: Progresso ID
          type: integer
          required: true
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/body_response'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/body_response_error_401'
        404:
          description: Not Found
          schema:
            $ref: '#/definitions/body_response_error_404'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/body_response_error_500'
    put:
      tags:
        - Criança Specs
      summary: Atualiza um progresso pelo ID
      operationId: putProgressById
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: id
          in: path
          description: Progresso ID
          type: integer
          required: true
        - in: body
          name: progress
          description: Persiste um novo progresso de crescimento do paciente
          required: true
          schema:
            $ref: '#/definitions/body_request'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/body_response'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/body_response_error_400'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/body_response_error_401'
        404:
          description: Not Found
          schema:
            $ref: '#/definitions/body_response_error_404'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/body_response_error_500'
    delete:
      tags:
        - Criança Specs
      summary: Excluir um progresso pelo ID
      operationId: delProgressById
      parameters:
        - name: id
          in: path
          description: Progresso ID
          type: integer
          required: true
      responses:
        204:
          description: Accepted
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/body_response_error_401'
        404:
          description: Not Found
          schema:
            $ref: '#/definitions/body_response_error_404'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/body_response_error_500'
securityDefinitions:
  token:
    type: apiKey
    in: header
    name: token
    description: Token Oauth2 no header 'XEGcM8qhkEmy3zAVHkqcRKp5m0u0'
definitions:
  body_response:
    type: object
    required:
      - account
      - dateProgress
      - headCircumference
      - height
      - id
      - weight
    properties:
      id:
        type: integer
        format: int32
        example: 1
      height:
        type: number
      weight:
        type: number
        example: 45
      headCircumference:
        type: number
      dateProgress:
        type: string
        format: date
      account:
        $ref: '#/definitions/body_response_account'
  body_request:
    type: object
    required:
      - account
      - dateProgress
      - headCircumference
      - height
      - weight
    properties:
      height:
        type: number
      weight:
        type: number
        example: 45
      headCircumference:
        type: number
      dateProgress:
        type: string
        format: date
      account:
        $ref: '#/definitions/body_response_account'
  body_response_account:
    type: object
    properties:
      id:
        type: integer
        format: int32
        example: 1
      firstName:
        type: string
        example: First
      lastName:
        type: string
        example: Last
      email:
        type: string
        format: email
        example: admin@admin.com
      dateBirth:
        type: string
        format: date
      gender:
        type: string
        example: M
        enum:
          - M
          - F
  body_response_error_400:
    type: object
    required:
      - message
    properties:
      message:
        type: string
        example: Request body com problemas, verefique o JSON account enviado
  body_response_error_401:
    type: object
    required:
      - message
    properties:
      message:
        type: string
        example: Token enviado invalido ou expirado
  body_response_error_404:
    type: object
    required:
      - message
    properties:
      message:
        type: string
        example: Recurso {id} não encontrado
  body_response_error_500:
    type: object
    required:
      - message
    properties:
      message:
        type: string
        example: Erro no processo de request da API verifique o log do servidor
